### ISSUE TITLE
Invalid autoloader

### ISSUE THREAD

**Issue by alexcagliari87** [cristianmarint/MotionGym#8]
Hi,
after cloning your repo at the first composer install i have this error and i can't continue to install this app.
Please check this:

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
PHP Warning:  Uncaught ErrorException: require(/var/www/html/MotionGym/vendor/composer/../../App/Http/Helpers.php): failed to open stream: No such file or directory in /var/www/html/MotionGym/vendor/composer/autoload_real.php:69
Stack trace:
#0 /var/www/html/MotionGym/vendor/composer/autoload_real.php(69): Composer\Util\ErrorHandler::handle(2, 'require(/var/ww...', '/var/www/html/M...', 69, Array)
#1 /var/www/html/MotionGym/vendor/composer/autoload_real.php(69): require()
#2 /var/www/html/MotionGym/vendor/composer/autoload_real.php(59): composerRequire22976e1edcdfa6a30f7e0bae6c8df695('307a8353bcbdf62...', '/var/www/html/M...')
#3 /var/www/html/MotionGym/vendor/autoload.php(7): ComposerAutoloaderInit22976e1edcdfa6a30f7e0bae6c8df695::getLoader()
#4 /var/www/html/MotionGym/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(43): require_once('/var/www/html/M...')
#5 phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php(305): Illuminate\Foundation\ComposerScripts::postAutoloadDump(O in /var/www/html/MotionGym/vendor/composer/autoload_real.php on line 69
```

**Comment by cristianmarint** [comment]
Hey Alex, I've been looking at the issue you reported, I've found a possible cause which is line 45 @compose.json, anyway.

I would recommend following the development environment installation guide if you want to test the platform.
